AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Creating basic backend environment.
# Parameters:
#   ApiPath:
#     Description: "auth api path"
#     Type: String
  
Resources:
  LLM:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./src/llm/template.yml
      # Parameters:
      #   ApiPath: !Sub ${ApiPath}
