AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Creating basic backend environment.
Parameters:
  EnvName:
    Description: "Your environment name here"
    Type: String
  AuthApiPath:
    Description: "auth api path"
    Type: String
  AuthServiceApiPath:
    Description: "auth service api path"
    Type: String
  AuthServiceApiHost:
    Description: "auth service api hpst"
    Type: String
  AuthServiceApiAccessKey:
    Description: "auth api access key"
    Type: String
  AuthServiceApiSercretAccessKey:
    Description: "auth api sercret access key"
    Type: String
  NotifySource:
    Description: "email notification source"
    Type: String
  StreamApiId:
    Description: "AI BOX's ID"
    Type: String
  StreamApiPw:
    Description: "AI BOX's password"
    Type: String
  AppApiAcmArn:
    Type: String
    Default: ""
  StreamApiAcmArn:
    Type: String
    Default: ""

Conditions:
  NotFeature: !Or
    - !Equals [!Ref EnvName, "production"]
    - !Equals [!Ref EnvName, "staging"]
    - !Equals [!Ref EnvName, "develop"]

Resources:
  # CommonLayer:
  #   Type: AWS::Serverless::LayerVersion
  #   Properties:
  #     LayerName: !Sub BI_common-layer-${EnvName}
  #     Description: Common Application Resource Layer
  #     ContentUri: ./src/layer

  VisitorTrend:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./src/trend/template.yaml
      Parameters:
        EnvName: !Sub ${EnvName}
        layer: !Ref CommonLayer

  API:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./resourses/api.yml
      Parameters:
        EnvName: !Sub ${EnvName}
        AuthApiPath: !Sub ${AuthApiPath}
        layer: !Ref CommonLayer
        CloudWatchRoleArn: !GetAtt Security.Outputs.AppApiRoleArn
        AcmArn: !Ref AppApiAcmArn

