name: "sam-deploy"

runs:
  using: "composite"
  steps:
    - run: |
        sam deploy --no-confirm-changeset \
            --no-fail-on-empty-changeset \
            --stack-name deploy-resources-llm \
            --s3-bucket llm-finetune-deploy-bucket
      shell: bash